language: cpp

os: osx

osx_image: xcode9

before_install:
  - brew update
  - brew install openssl
  - brew install boost@1.60
  - brew unlink boost@1.60

script:
  - cd "$TRAVIS_BUILD_DIR/platform/macos" && xcodebuild
  



